In [1]:
import numpy as np

x = np.array([1,2,3])
print(x)

[1 2 3]


In [3]:
# 크기가 (1,3)인 2차원
np.array([1,2,3])

array([1, 2, 3])

In [4]:
# 크기가 (1,3)인 2차원 열벡터
np.array([[1],[2],[3]])

array([[1],
       [2],
       [3]])

In [8]:
from scipy import linalg

s = np.array([2,3,1])

In [9]:
# 단위 벡터 - 1을 만드는 작업 / norm(1) 절대값, norm(2) 제곱 ?
s / linalg.norm(s)

array([0.53452248, 0.80178373, 0.26726124])

In [11]:
# Norm
x = np.array([1,-3])
x / linalg.norm(x)

array([ 0.31622777, -0.9486833 ])

In [13]:
# Norm 2
x / (x**2).sum()**0.5

array([ 0.31622777, -0.9486833 ])

In [14]:
# 영 벡터 (zeros())

In [16]:
np.zeros(5) # 실수로 반환

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros(5).shape # 5행 1열

(5,)

In [19]:
s = (2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

In [26]:
# 선형 독립, 선형 종속
# Rank

# matrix_rank()

x_1 = np.array([[2,7],[5,1]])
np.linalg.matrix_rank(x)

1

In [27]:
x_2 = np.array([[2,4],[3,6]])
np.linalg.matrix_rank(x)

1

In [28]:
x_3 = np.array([[1,2],[3,5]])
np.linalg.matrix_rank(x)

1

In [30]:
# 벡터의 내적과 외적

x = [2,3]
y = [3,1]

# 벡터의 덧셈, 뺄셈 (zip 함수)

z = [i+j for i, j in zip(x,y)] # list comprehension?
print(z)

[5, 4]


In [33]:
z_2 = [i-j for i,j in zip(x,y)]
print(z_2)

[-1, 2]


In [34]:
# 벡터의 곱셈 (inner product, outer product)

x = [3,4]
c = 8

z = [c*i for i in x]
print(z)

[24, 32]


In [35]:
# 내적 (inner product) 가장 많이 사용됨

u = np.array([6,6])  # (1,2)
v = np.array([12,0])  # (2,1)

np.dot(u,v)  # (1,1) - 크기

72

In [31]:
# zip 함수

list(zip([1,2,3],[4,5,6]))

[(1, 4), (2, 5), (3, 6)]

In [32]:
list(zip([1,2,3],[4,5,6],[7,8,9]))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [7]:
# 벡터의 내적 원리

import numpy as np

A = np.arange(1*2*3).reshape((1,2,3)) # A의 마지막 축과, B의 뒤에서 2번째 축으로 계산
B1 = np.arange(1*2*3).reshape((1,2,3))
B2 = np.arange(1*2*3).reshape((1,3,2))
B3 = np.arange(1*2*3).reshape((2,1,3))
B4 = np.arange(1*2*3).reshape((2,3,1))
B5 = np.arange(1*2*3).reshape((3,1,2))
B6 = np.arange(1*2*3).reshape((3,2,1))

In [4]:
np.arange(1*2*3)

array([0, 1, 2, 3, 4, 5])

In [5]:
np.arange(1*2*3).reshape((1,2,3))

array([[[0, 1, 2],
        [3, 4, 5]]])

In [10]:
np.arange(1*2*3).reshape((1,3,2))

array([[[0, 1],
        [2, 3],
        [4, 5]]])

In [18]:
# np.dot(A,B1) # value error 발생

In [9]:
np.dot(A,B2)

array([[[[10, 13]],

        [[28, 40]]]])

In [12]:
# np.dot(A,B3) # value error 발생

In [13]:
np.dot(A,B4)

array([[[[ 5],
         [14]],

        [[14],
         [50]]]])

In [15]:
# np.dot(A,B5) # value error 발생

In [17]:
# np.dot(A,B6) # value error 발생

In [19]:
# dot-product 내적
import numpy as np

u = np.array([3,-6])
v = np.array([-7,9])
uv = np.dot(u,v)
print(uv)

-75


In [20]:
# 외적 (cross() 함수 적용)

a = (1,3,5)
b = (2,4,6)

def cross(a,b):
    c = [a[1]*b[2]-a[2]*b[1],
         a[2]*b[0]-a[0]*b[2],
         a[0]*b[1]-a[1]*b[0]]
    return c

In [21]:
cross(a,b)

[-2, 4, -2]

In [22]:
# numpy 이용 벡터 외적 구하기
import numpy as np
print(np.cross(a,b))

[-2  4 -2]


In [23]:
# 직교 벡터
import numpy as np

# 크기가 (1,2)인 2차원 배열

a = np.array([1,2])
print(a)

[1 2]


In [24]:
np.linalg.norm(a) # a의 길이

2.23606797749979

In [25]:
# L1 norm

np.linalg.norm(a, ord=1)

3.0

In [26]:
# L2 norm

np.linalg.norm(a, ord=2)

2.23606797749979

In [27]:
# 유클리디언 거리 구하기

from scipy.spatial import distance

p1 = (1,2,3)
p2 = (4,5,6)

# p1, p2 사이 유클리디언 거리
distance.euclidean(p1,p2)

5.196152422706632

In [31]:
# 맨해튼 거리

from math import *

p1 = (1,2,3)
p2 = (4,5,6)

# p1, p2 사이 맨해튼거리

def manhattan_dist(x,y):
    return sum(abs(a-b) for a,b in zip(x,y))

In [32]:
manhattan_dist(p1,p2)

9

In [34]:
# 코사인 유사도 - 문서 유사도

from numpy import dot
from numpy.linalg import norm
import numpy as np

def cos_sim(A,B):
    return dot(A,B)/(norm(A)*norm(B)) # cosAB / normAB

In [38]:
doc1 = np.array([1,1,1,1,0])
doc2 = np.array([1,0,1,0,1])
doc3 = np.array([2,1,1,1,1])

In [39]:
# 코사인 함수에 따라 문서간 유사도 출력하기

print(cos_sim(doc1, doc2))
print(cos_sim(doc1, doc3)) # 유사도가 가장 높음
print(cos_sim(doc2, doc3))

0.5773502691896258
0.8838834764831843
0.8164965809277259
